### PR TITLE
Create 2024-09-13-junit-ext-and-kafka4.md

### PR DESCRIPTION
**Pull request by k-wall**
Blog post about https://github.com/kroxylicious/kroxylicious-junit5-extension/issues/389

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
Think the post should make it clearer that were are only really discussing in memory usage but will continue to support zookeeper and older broker clusters in vm mode

**Comment by k-wall** [comment]
> Think the post should make it clearer that were are only really discussing in memory usage but will continue to support zookeeper and older broker clusters in vm mode

If it turns out no one cares are Zookeeper at all, why not kill both container and in-VM paths?  Fewer lines of code to maintain.

**Comment by SamBarker** [comment]
> > Think the post should make it clearer that were are only really discussing in memory usage but will continue to support zookeeper and older broker clusters in vm mode
> 
> 
> 
> If it turns out no one cares are Zookeeper at all, why not kill both container and in-VM paths?  Fewer lines of code to maintain.

No particular reason but that was my take away from the call, we were only going to remove in memory support not container.

**Comment by k-wall** [comment]
Let's see what feedback comes back.

**Pull request merged**
