### PR TITLE
Fix link to GitHub repo in the footer

### PR DESCRIPTION
**Pull request by ppatierno**

### CODE REVIEW

**Review by k-wall — COMMENTED** [review]
I _think_ the list forming under "supporting" comprises entities and organisation that somehow support kroxylicious existence, with github.con being the first.  As such I think linking to github.com is the right, in the context.

**Comment by ppatierno** [comment]
So I got confused about the purpose of it. I was referring to something similar we have on the https://strimzi.io/ (top right side) where we have links and one of them is using GitHub icon but pointing to Strimzi repo.
I see your reference to GitHub repo could be easily lost in the text a few lines above together with the Slack one.
I think using recognizable icons for visitors is much better ... I got confused as it could happen to any other visitor imho.

**Review by SamBarker — APPROVED** [review]
While I agree with @k-wall's description I think its fine to point the icon to our repo anyway. 

I'm leaving the final decision to @gracegrimwood

**Review by gracegrimwood — APPROVED** [review]
Yeah I think it's fine to point the icon to the repo. In the context (which is thanking GitHub for hosting the repo and site, I guess) it makes just as much sense as linking to the GitHub homepage IMHO.

Thanks for pointing this out Paolo! 🙂

**Review by k-wall — APPROVED** [review]

**Pull request merged**
